// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_framework.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_rpc_5fframework_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_rpc_5fframework_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021011 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_rpc_5fframework_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_rpc_5fframework_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_rpc_5fframework_2eproto;
namespace wa {
namespace rpc {
class FrameworkRequestHeader;
struct FrameworkRequestHeaderDefaultTypeInternal;
extern FrameworkRequestHeaderDefaultTypeInternal _FrameworkRequestHeader_default_instance_;
class FrameworkResponseHeader;
struct FrameworkResponseHeaderDefaultTypeInternal;
extern FrameworkResponseHeaderDefaultTypeInternal _FrameworkResponseHeader_default_instance_;
}  // namespace rpc
}  // namespace wa
PROTOBUF_NAMESPACE_OPEN
template<> ::wa::rpc::FrameworkRequestHeader* Arena::CreateMaybeMessage<::wa::rpc::FrameworkRequestHeader>(Arena*);
template<> ::wa::rpc::FrameworkResponseHeader* Arena::CreateMaybeMessage<::wa::rpc::FrameworkResponseHeader>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace wa {
namespace rpc {

// ===================================================================

class FrameworkRequestHeader final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:wa.rpc.FrameworkRequestHeader) */ {
 public:
  inline FrameworkRequestHeader() : FrameworkRequestHeader(nullptr) {}
  ~FrameworkRequestHeader() override;
  explicit PROTOBUF_CONSTEXPR FrameworkRequestHeader(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FrameworkRequestHeader(const FrameworkRequestHeader& from);
  FrameworkRequestHeader(FrameworkRequestHeader&& from) noexcept
    : FrameworkRequestHeader() {
    *this = ::std::move(from);
  }

  inline FrameworkRequestHeader& operator=(const FrameworkRequestHeader& from) {
    CopyFrom(from);
    return *this;
  }
  inline FrameworkRequestHeader& operator=(FrameworkRequestHeader&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FrameworkRequestHeader& default_instance() {
    return *internal_default_instance();
  }
  static inline const FrameworkRequestHeader* internal_default_instance() {
    return reinterpret_cast<const FrameworkRequestHeader*>(
               &_FrameworkRequestHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FrameworkRequestHeader& a, FrameworkRequestHeader& b) {
    a.Swap(&b);
  }
  inline void Swap(FrameworkRequestHeader* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FrameworkRequestHeader* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FrameworkRequestHeader* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FrameworkRequestHeader>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FrameworkRequestHeader& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FrameworkRequestHeader& from) {
    FrameworkRequestHeader::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FrameworkRequestHeader* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "wa.rpc.FrameworkRequestHeader";
  }
  protected:
  explicit FrameworkRequestHeader(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServiceNameFieldNumber = 1,
    kMethodNameFieldNumber = 2,
    kArgsSizeFieldNumber = 3,
  };
  // bytes serviceName = 1;
  void clear_servicename();
  const std::string& servicename() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_servicename(ArgT0&& arg0, ArgT... args);
  std::string* mutable_servicename();
  PROTOBUF_NODISCARD std::string* release_servicename();
  void set_allocated_servicename(std::string* servicename);
  private:
  const std::string& _internal_servicename() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_servicename(const std::string& value);
  std::string* _internal_mutable_servicename();
  public:

  // bytes methodName = 2;
  void clear_methodname();
  const std::string& methodname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_methodname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_methodname();
  PROTOBUF_NODISCARD std::string* release_methodname();
  void set_allocated_methodname(std::string* methodname);
  private:
  const std::string& _internal_methodname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_methodname(const std::string& value);
  std::string* _internal_mutable_methodname();
  public:

  // uint32 argsSize = 3;
  void clear_argssize();
  uint32_t argssize() const;
  void set_argssize(uint32_t value);
  private:
  uint32_t _internal_argssize() const;
  void _internal_set_argssize(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:wa.rpc.FrameworkRequestHeader)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr servicename_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr methodname_;
    uint32_t argssize_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rpc_5fframework_2eproto;
};
// -------------------------------------------------------------------

class FrameworkResponseHeader final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:wa.rpc.FrameworkResponseHeader) */ {
 public:
  inline FrameworkResponseHeader() : FrameworkResponseHeader(nullptr) {}
  ~FrameworkResponseHeader() override;
  explicit PROTOBUF_CONSTEXPR FrameworkResponseHeader(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FrameworkResponseHeader(const FrameworkResponseHeader& from);
  FrameworkResponseHeader(FrameworkResponseHeader&& from) noexcept
    : FrameworkResponseHeader() {
    *this = ::std::move(from);
  }

  inline FrameworkResponseHeader& operator=(const FrameworkResponseHeader& from) {
    CopyFrom(from);
    return *this;
  }
  inline FrameworkResponseHeader& operator=(FrameworkResponseHeader&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FrameworkResponseHeader& default_instance() {
    return *internal_default_instance();
  }
  static inline const FrameworkResponseHeader* internal_default_instance() {
    return reinterpret_cast<const FrameworkResponseHeader*>(
               &_FrameworkResponseHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(FrameworkResponseHeader& a, FrameworkResponseHeader& b) {
    a.Swap(&b);
  }
  inline void Swap(FrameworkResponseHeader* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FrameworkResponseHeader* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FrameworkResponseHeader* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FrameworkResponseHeader>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FrameworkResponseHeader& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FrameworkResponseHeader& from) {
    FrameworkResponseHeader::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FrameworkResponseHeader* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "wa.rpc.FrameworkResponseHeader";
  }
  protected:
  explicit FrameworkResponseHeader(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCodeFieldNumber = 1,
    kResponseSizeFieldNumber = 2,
  };
  // uint32 code = 1;
  void clear_code();
  uint32_t code() const;
  void set_code(uint32_t value);
  private:
  uint32_t _internal_code() const;
  void _internal_set_code(uint32_t value);
  public:

  // uint32 responseSize = 2;
  void clear_responsesize();
  uint32_t responsesize() const;
  void set_responsesize(uint32_t value);
  private:
  uint32_t _internal_responsesize() const;
  void _internal_set_responsesize(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:wa.rpc.FrameworkResponseHeader)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t code_;
    uint32_t responsesize_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rpc_5fframework_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FrameworkRequestHeader

// bytes serviceName = 1;
inline void FrameworkRequestHeader::clear_servicename() {
  _impl_.servicename_.ClearToEmpty();
}
inline const std::string& FrameworkRequestHeader::servicename() const {
  // @@protoc_insertion_point(field_get:wa.rpc.FrameworkRequestHeader.serviceName)
  return _internal_servicename();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FrameworkRequestHeader::set_servicename(ArgT0&& arg0, ArgT... args) {
 
 _impl_.servicename_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:wa.rpc.FrameworkRequestHeader.serviceName)
}
inline std::string* FrameworkRequestHeader::mutable_servicename() {
  std::string* _s = _internal_mutable_servicename();
  // @@protoc_insertion_point(field_mutable:wa.rpc.FrameworkRequestHeader.serviceName)
  return _s;
}
inline const std::string& FrameworkRequestHeader::_internal_servicename() const {
  return _impl_.servicename_.Get();
}
inline void FrameworkRequestHeader::_internal_set_servicename(const std::string& value) {
  
  _impl_.servicename_.Set(value, GetArenaForAllocation());
}
inline std::string* FrameworkRequestHeader::_internal_mutable_servicename() {
  
  return _impl_.servicename_.Mutable(GetArenaForAllocation());
}
inline std::string* FrameworkRequestHeader::release_servicename() {
  // @@protoc_insertion_point(field_release:wa.rpc.FrameworkRequestHeader.serviceName)
  return _impl_.servicename_.Release();
}
inline void FrameworkRequestHeader::set_allocated_servicename(std::string* servicename) {
  if (servicename != nullptr) {
    
  } else {
    
  }
  _impl_.servicename_.SetAllocated(servicename, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.servicename_.IsDefault()) {
    _impl_.servicename_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:wa.rpc.FrameworkRequestHeader.serviceName)
}

// bytes methodName = 2;
inline void FrameworkRequestHeader::clear_methodname() {
  _impl_.methodname_.ClearToEmpty();
}
inline const std::string& FrameworkRequestHeader::methodname() const {
  // @@protoc_insertion_point(field_get:wa.rpc.FrameworkRequestHeader.methodName)
  return _internal_methodname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FrameworkRequestHeader::set_methodname(ArgT0&& arg0, ArgT... args) {
 
 _impl_.methodname_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:wa.rpc.FrameworkRequestHeader.methodName)
}
inline std::string* FrameworkRequestHeader::mutable_methodname() {
  std::string* _s = _internal_mutable_methodname();
  // @@protoc_insertion_point(field_mutable:wa.rpc.FrameworkRequestHeader.methodName)
  return _s;
}
inline const std::string& FrameworkRequestHeader::_internal_methodname() const {
  return _impl_.methodname_.Get();
}
inline void FrameworkRequestHeader::_internal_set_methodname(const std::string& value) {
  
  _impl_.methodname_.Set(value, GetArenaForAllocation());
}
inline std::string* FrameworkRequestHeader::_internal_mutable_methodname() {
  
  return _impl_.methodname_.Mutable(GetArenaForAllocation());
}
inline std::string* FrameworkRequestHeader::release_methodname() {
  // @@protoc_insertion_point(field_release:wa.rpc.FrameworkRequestHeader.methodName)
  return _impl_.methodname_.Release();
}
inline void FrameworkRequestHeader::set_allocated_methodname(std::string* methodname) {
  if (methodname != nullptr) {
    
  } else {
    
  }
  _impl_.methodname_.SetAllocated(methodname, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.methodname_.IsDefault()) {
    _impl_.methodname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:wa.rpc.FrameworkRequestHeader.methodName)
}

// uint32 argsSize = 3;
inline void FrameworkRequestHeader::clear_argssize() {
  _impl_.argssize_ = 0u;
}
inline uint32_t FrameworkRequestHeader::_internal_argssize() const {
  return _impl_.argssize_;
}
inline uint32_t FrameworkRequestHeader::argssize() const {
  // @@protoc_insertion_point(field_get:wa.rpc.FrameworkRequestHeader.argsSize)
  return _internal_argssize();
}
inline void FrameworkRequestHeader::_internal_set_argssize(uint32_t value) {
  
  _impl_.argssize_ = value;
}
inline void FrameworkRequestHeader::set_argssize(uint32_t value) {
  _internal_set_argssize(value);
  // @@protoc_insertion_point(field_set:wa.rpc.FrameworkRequestHeader.argsSize)
}

// -------------------------------------------------------------------

// FrameworkResponseHeader

// uint32 code = 1;
inline void FrameworkResponseHeader::clear_code() {
  _impl_.code_ = 0u;
}
inline uint32_t FrameworkResponseHeader::_internal_code() const {
  return _impl_.code_;
}
inline uint32_t FrameworkResponseHeader::code() const {
  // @@protoc_insertion_point(field_get:wa.rpc.FrameworkResponseHeader.code)
  return _internal_code();
}
inline void FrameworkResponseHeader::_internal_set_code(uint32_t value) {
  
  _impl_.code_ = value;
}
inline void FrameworkResponseHeader::set_code(uint32_t value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:wa.rpc.FrameworkResponseHeader.code)
}

// uint32 responseSize = 2;
inline void FrameworkResponseHeader::clear_responsesize() {
  _impl_.responsesize_ = 0u;
}
inline uint32_t FrameworkResponseHeader::_internal_responsesize() const {
  return _impl_.responsesize_;
}
inline uint32_t FrameworkResponseHeader::responsesize() const {
  // @@protoc_insertion_point(field_get:wa.rpc.FrameworkResponseHeader.responseSize)
  return _internal_responsesize();
}
inline void FrameworkResponseHeader::_internal_set_responsesize(uint32_t value) {
  
  _impl_.responsesize_ = value;
}
inline void FrameworkResponseHeader::set_responsesize(uint32_t value) {
  _internal_set_responsesize(value);
  // @@protoc_insertion_point(field_set:wa.rpc.FrameworkResponseHeader.responseSize)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace rpc
}  // namespace wa

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_rpc_5fframework_2eproto
